version: '3'

services:
  web:
    container_name: rbg-web
    env_file:
      - redbuttegarden/.env.dev
    build: redbuttegarden/
    volumes:
      - ./redbuttegarden:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: gunicorn --pythonpath redbuttegarden redbuttegarden.wsgi:application --bind 0.0.0.0:8000 --workers 3
  db:
    container_name: rbg-db
    image: "postgres:12.7"
    env_file:
      - redbuttegarden/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - '5432:5432'
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart:
      unless-stopped
    depends_on:
      - web
    volumes:
      - static_volume:/home/static
      - media_volume:/home/media
      - ./nginx/certs:/etc/ssl/certs


volumes:
  postgres_data:
  static_volume:
  media_volume:
